In [2]:
import pandas as pd

In [3]:
# ./bus_crawling/01_data_원본/trfcard (0)폴더의 trfcard.csv 파일읽기
file_path = './bus_crawling/01_data_원본/trfcard (0)/'
df_bus_card_org = pd.read_csv(file_path + 'trfcard.csv')
df_bus_card_org.head()

,on_date,off_date,route_name,descr,age_type,trans_yn,addfee_yn,start_bstop,start_gps_x,start_gps_y,end_bstop,end_gps_x,end_gps_y
0,20200102051049,20200102051844,131,양덕-송도-시청-양학-양덕,일반,N,N,양덕차고지,129.401693,36.077258,동부초등학교,129.380866,36.062209
1,20200102051338,20200102054549,175,문덕-고속터미널-선린병원-달전,일반,N,N,문덕사거리,129.403178,35.962298,새마을금고해도지점,129.370626,36.015468
2,20200102051549,20200102051930,160,문덕-대송-송도-죽도-용흥,일반,N,N,문덕사거리,129.403442,35.962846,성우오토모티브,129.384492,35.972675
3,20200102051617,20200102055046,175,문덕-고속터미널-선린병원-달전,일반,N,N,부영사랑3차,129.402520,35.973038,오거리,129.366312,36.031816
4,20200102051841,20200102052310,102,문덕-남구청-고속터미널-북구보건소-양덕,일반,N,N,문덕온천,129.406532,35.961964,용덕사거리,129.415174,35.972826

In [4]:
df_bus_card_org.describe()

,on_date,off_date,start_gps_x,start_gps_y,end_gps_x,end_gps_y
count,1.618500e+04,1.618500e+04,16185.000000,16185.000000,16185.000000,16185.000000
mean,2.020010e+13,2.020010e+13,129.369118,36.034985,129.368939,36.031927
std,4.127644e+04,4.175148e+04,0.048054,0.043280,0.040777,0.033987
min,2.020010e+13,2.020010e+13,129.052958,35.804119,129.052958,35.804119
25%,2.020010e+13,2.020010e+13,129.350290,36.012537,129.353856,36.013250
50%,2.020010e+13,2.020010e+13,129.365461,36.031720,129.365281,36.034110
75%,2.020010e+13,2.020010e+13,129.383462,36.064088,129.370823,36.046050
max,2.020010e+13,2.020010e+13,129.578137,36.254158,129.578137,36.244762

#### 버스 항목명 변경

In [5]:
# 1-컬럼명 변경(딕셔너리)
"""
{'on_date' : '승차시각',
'off_date' : '하차시각',
'route_name' : '노선명',
'descr' : '노선설명',
'age_type' : '승객연령',
'trans_yn' : '환승여부',
'addfee_yn' : '추가운임여부',
'start_bstop' : '승차정류장',
'start_gps_x' : '승차정류장 GPS X',
'start_gps_y' : '승차정류장 GPS Y',
'end_bstop' : '하차정류장',
'end_gps_x' : '하차정류장 GPS X',
'end_gps_y' : '하차정류장 GPS Y'}

"""
meta_path = './bus_crawling/01_data_원본/trfcard (0)/'
df_bus_card_col_org = pd.read_excel(file_path + 'trfcard_columns.xlsx',header = 2, usecols=('B:C'))

df_bus_card_col_org

       컬럼명 (영문)     컬럼명 (한글)
0       on_date         승차시각
1      off_date         하차시각
2    route_name          노선명
3         descr         노선설명
4      age_type         승객연령
5      trans_yn         환승여부
6     addfee_yn       추가운임여부
7   start_bstop        승차정류장
8   start_gps_x  승차정류장 GPS X
9   start_gps_y  승차정류장 GPS Y
10    end_bstop        하차정류장
11    end_gps_x  하차정류장 GPS X
12    end_gps_y  하차정류장 GPS Y

In [6]:
# 데이터프레임을 딕셔너리로 변환
df_bus_card_col_new_dict = {}
for k,v in zip(df_bus_card_col_org['컬럼명 (영문)'],df_bus_card_col_org['컬럼명 (한글)']):
    df_bus_card_col_new_dict[k] = v

df_bus_card_col_new_dict

{'on_date': '승차시각',
 'off_date': '하차시각',
 'route_name': '노선명',
 'descr': '노선설명',
 'age_type': '승객연령',
 'trans_yn': '환승여부',
 'addfee_yn': '추가운임여부',
 'start_bstop': '승차정류장',
 'start_gps_x': '승차정류장 GPS X',
 'start_gps_y': '승차정류장 GPS Y',
 'end_bstop': '하차정류장',
 'end_gps_x': '하차정류장 GPS X',
 'end_gps_y': '하차정류장 GPS Y'}

In [7]:
# 항목명 변경
df_bus_card_kor = df_bus_card_org.rename(columns = df_bus_card_col_new_dict)

In [8]:
df_bus_card_kor.head(3)

,승차시각,하차시각,노선명,노선설명,승객연령,환승여부,추가운임여부,승차정류장,승차정류장 GPS X,승차정류장 GPS Y,하차정류장,하차정류장 GPS X,하차정류장 GPS Y
0,20200102051049,20200102051844,131,양덕-송도-시청-양학-양덕,일반,N,N,양덕차고지,129.401693,36.077258,동부초등학교,129.380866,36.062209
1,20200102051338,20200102054549,175,문덕-고속터미널-선린병원-달전,일반,N,N,문덕사거리,129.403178,35.962298,새마을금고해도지점,129.370626,36.015468
2,20200102051549,20200102051930,160,문덕-대송-송도-죽도-용흥,일반,N,N,문덕사거리,129.403442,35.962846,성우오토모티브,129.384492,35.972675

In [9]:
# 2-컬럼명 변경(리스트)
col_name = ['승차시각' , '하차시각' , '노선명' , '노선설명' , '승객연령' , '환승여부' , '추가운임여부' , '승차정류장' , '승차정류장 GPS X' , '승차정류장 GPS Y' , '하차정류장' , '하차정류장 GPS X' , '하차정류장 GPS Y']
df_bus_card_org.columns = col_name
df_bus_card_org.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16185 entries, 0 to 16184
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   승차시각         16185 non-null  int64
 1   하차시각         16185 non-null  int64
 2   노선명          16185 non-null  object
 3   노선설명         16185 non-null  object
 4   승객연령         16185 non-null  object
 5   환승여부         16185 non-null  object
 6   추가운임여부       16185 non-null  object
 7   승차정류장        16185 non-null  object
 8   승차정류장 GPS X  16185 non-null  float64
 9   승차정류장 GPS Y  16185 non-null  float64
 10  하차정류장        16185 non-null  object
 11  하차정류장 GPS X  16185 non-null  float64
 12  하차정류장 GPS Y  16185 non-null  float64
dtypes: float64(4), int64(2), object(7)
memory usage: 1.6+ MB

In [65]:
df_bus_card_kor.head(3)

,승차시각,하차시각,노선명,노선설명,승객연령,환승여부,추가운임여부,승차정류장,승차정류장 GPS X,승차정류장 GPS Y,하차정류장,하차정류장 GPS X,하차정류장 GPS Y
0,20200102051049,20200102051844,131,양덕-송도-시청-양학-양덕,일반,N,N,양덕차고지,129.401693,36.077258,동부초등학교,129.380866,36.062209
1,20200102051338,20200102054549,175,문덕-고속터미널-선린병원-달전,일반,N,N,문덕사거리,129.403178,35.962298,새마을금고해도지점,129.370626,36.015468
2,20200102051549,20200102051930,160,문덕-대송-송도-죽도-용흥,일반,N,N,문덕사거리,129.403442,35.962846,성우오토모티브,129.384492,35.972675

In [10]:
df_bus_card_kor['승객연령'].unique()

array(['일반', '청소년', 'None', '어린이'], dtype=object)

In [11]:
df_bus_card_kor.iloc[0,0]

20200102051049

#### 버스이용량 분석 항목 생성

In [75]:
# 1. 기준월 및 기준일자별 분석이용량 분석
# 2. 기준일 및 기준시간대별 버스 이용량 분석
# 3. 기준시간 및 시간(분)별 버스 이용량 분석

#### 버스내 체류시간

In [76]:
# 1. 기준일 및 시간대별 버스내 체류시간(분) 분석비교
# 2. 시간대별 및 승객구분별 버스내 체류시간(분) 분석비교
# 3. 시간 및 승객구분별 빈도분석 비교

#### 승하차정류장별 버스내 체류시간

In [80]:
# 1.승하차 정류장별 버스내 체류시간(분) 상위 30건 비교분석

In [12]:
df_bus_card_kor.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16185 entries, 0 to 16184
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   승차시각         16185 non-null  int64
 1   하차시각         16185 non-null  int64
 2   노선명          16185 non-null  object
 3   노선설명         16185 non-null  object
 4   승객연령         16185 non-null  object
 5   환승여부         16185 non-null  object
 6   추가운임여부       16185 non-null  object
 7   승차정류장        16185 non-null  object
 8   승차정류장 GPS X  16185 non-null  float64
 9   승차정류장 GPS Y  16185 non-null  float64
 10  하차정류장        16185 non-null  object
 11  하차정류장 GPS X  16185 non-null  float64
 12  하차정류장 GPS Y  16185 non-null  float64
dtypes: float64(4), int64(2), object(7)
memory usage: 1.6+ MB

In [100]:
# 1. 정수항목을 문자항목으로 변환하여 신규 생성
df_bus_card_kor['승차시각_문자'] = df_bus_card_kor['승차시각'].astype('string')
df_bus_card_kor['하차시각_문자'] = df_bus_card_kor['하차시각'].astype('string')

In [114]:
df_bus_card_kor['승차시각_년도'] = df_bus_card_kor['승차시각_문자'].str[0:4]
df_bus_card_kor['승차시각_월'] = df_bus_card_kor['승차시각_문자'].str[4:6]
df_bus_card_kor['승차시각_일'] = df_bus_card_kor['승차시각_문자'].str[6:8]
df_bus_card_kor['승차시각_시'] = df_bus_card_kor['승차시각_문자'].str[8:10]
df_bus_card_kor['승차시각_분'] = df_bus_card_kor['승차시각_문자'].str[10:12]
df_bus_card_kor['승차시각_초'] = df_bus_card_kor['승차시각_문자'].str[12:14]
df_bus_card_kor['하차시각_년도'] = df_bus_card_kor['하차시각_문자'].str[0:4]
df_bus_card_kor['하차시각_월'] = df_bus_card_kor['하차시각_문자'].str[4:6]
df_bus_card_kor['하차시각_일'] = df_bus_card_kor['하차시각_문자'].str[6:8]
df_bus_card_kor['하차시각_시'] = df_bus_card_kor['하차시각_문자'].str[8:10]
df_bus_card_kor['하차시각_분'] = df_bus_card_kor['하차시각_문자'].str[10:12]
df_bus_card_kor['하차시각_초'] = df_bus_card_kor['하차시각_문자'].str[12:14]

In [113]:
df_bus_card_kor['승차시각_문자'].str[12:14]

0        49
1        38
2        49
3        17
4        41
         ..
16180    23
16181    49
16182    49
16183    18
16184    36
Name: 승차시각_문자, Length: 16185, dtype: string

In [115]:
df_bus_card_kor.head(3)

,승차시각,하차시각,노선명,노선설명,승객연령,환승여부,추가운임여부,승차정류장,승차정류장 GPS X,승차정류장 GPS Y,...,승차시각_일,하차시각_년도,하차시각_월,하차시각_일,승차시각_시,승차시각_분,승차시각_초,하차시각_시,하차시각_분,하차시각_초
0,20200102051049,20200102051844,131,양덕-송도-시청-양학-양덕,일반,N,N,양덕차고지,129.401693,36.077258,...,02,2020,01,02,05,10,49,05,18,44
1,20200102051338,20200102054549,175,문덕-고속터미널-선린병원-달전,일반,N,N,문덕사거리,129.403178,35.962298,...,02,2020,01,02,05,13,38,05,45,49
2,20200102051549,20200102051930,160,문덕-대송-송도-죽도-용흥,일반,N,N,문덕사거리,129.403442,35.962846,...,02,2020,01,02,05,15,49,05,19,30

In [19]:
for i in range(1,80):
    strt_path = './bus_crawling/01_data_원본/trfcard ('
    end_path = ')/trfcard.csv'
    tot_path = strt_path + str(i) + end_path
    print(tot_path)

./bus_crawling/01_data_원본/trfcard (1)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (2)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (3)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (4)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (5)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (6)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (7)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (8)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (9)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (10)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (11)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (12)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (13)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (14)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (15)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (16)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (17)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (18)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (19)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (20)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (21)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (22)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (23)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (24)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (25)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (26)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (27)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (28)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (29)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (30)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (31)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (32)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (33)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (34)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (35)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (36)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (37)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (38)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (39)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (40)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (41)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (42)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (43)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (44)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (45)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (46)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (47)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (48)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (49)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (50)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (51)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (52)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (53)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (54)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (55)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (56)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (57)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (58)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (59)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (60)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (61)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (62)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (63)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (64)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (65)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (66)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (67)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (68)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (69)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (70)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (71)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (72)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (73)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (74)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (75)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (76)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (77)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (78)/trfcard.csv
./bus_crawling/01_data_원본/trfcard (79)/trfcard.csv

#### 4월9 일 수업시작 ---

In [15]:
df_bus_card_kor.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16185 entries, 0 to 16184
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   승차시각         16185 non-null  int64
 1   하차시각         16185 non-null  int64
 2   노선명          16185 non-null  object
 3   노선설명         16185 non-null  object
 4   승객연령         16185 non-null  object
 5   환승여부         16185 non-null  object
 6   추가운임여부       16185 non-null  object
 7   승차정류장        16185 non-null  object
 8   승차정류장 GPS X  16185 non-null  float64
 9   승차정류장 GPS Y  16185 non-null  float64
 10  하차정류장        16185 non-null  object
 11  하차정류장 GPS X  16185 non-null  float64
 12  하차정류장 GPS Y  16185 non-null  float64
dtypes: float64(4), int64(2), object(7)
memory usage: 1.6+ MB

In [19]:
# 승차하시각 타입변환 : 정수 --> 문자
df_bus_card_kor = df_bus_card_kor.astype({'승차시각':'str'})
df_bus_card_kor = df_bus_card_kor.astype({'하차시각':'str'})
df_bus_card_kor.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16185 entries, 0 to 16184
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   승차시각         16185 non-null  object
 1   하차시각         16185 non-null  object
 2   노선명          16185 non-null  object
 3   노선설명         16185 non-null  object
 4   승객연령         16185 non-null  object
 5   환승여부         16185 non-null  object
 6   추가운임여부       16185 non-null  object
 7   승차정류장        16185 non-null  object
 8   승차정류장 GPS X  16185 non-null  float64
 9   승차정류장 GPS Y  16185 non-null  float64
 10  하차정류장        16185 non-null  object
 11  하차정류장 GPS X  16185 non-null  float64
 12  하차정류장 GPS Y  16185 non-null  float64
dtypes: float64(4), object(9)
memory usage: 1.6+ MB

In [21]:
# 분석에 필요한 항목을 타입변환하여 데이터프레임 추가 : 문자 --> 날짜
df_bus_cart = pd.DataFrame()

df_bus_cart['승차시각'] = pd.to_datetime(df_bus_card_kor['승차시각'])
df_bus_cart['하차시각'] = pd.to_datetime(df_bus_card_kor['하차시각'])
df_bus_cart['승객구분'] = df_bus_card_kor['승객연령']
df_bus_cart['환승여부'] = df_bus_card_kor['환승여부']
df_bus_cart['추가운임여부'] = df_bus_card_kor['추가운임여부']
df_bus_cart['승차정류장'] = df_bus_card_kor['승차정류장']
df_bus_cart['하차정류장'] = df_bus_card_kor['하차정류장']

df_bus_cart.head(3)

                 승차시각                하차시각 승객구분 환승여부 추가운임여부  승차정류장      하차정류장
0 2020-01-02 05:10:49 2020-01-02 05:18:44   일반    N      N  양덕차고지     동부초등학교
1 2020-01-02 05:13:38 2020-01-02 05:45:49   일반    N      N  문덕사거리  새마을금고해도지점
2 2020-01-02 05:15:49 2020-01-02 05:19:30   일반    N      N  문덕사거리    성우오토모티브

In [31]:
# 체류시간
df_bus_cart.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16185 entries, 0 to 16184
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   승차시각    16185 non-null  datetime64[ns]
 1   하차시각    16185 non-null  datetime64[ns]
 2   승객구분    16185 non-null  object
 3   환승여부    16185 non-null  object
 4   추가운임여부  16185 non-null  object
 5   승차정류장   16185 non-null  object
 6   하차정류장   16185 non-null  object
dtypes: datetime64[ns](2), object(5)
memory usage: 885.2+ KB

In [32]:
# 분단위로 데이터타입변환(분단위 - 소수 - 정수)
df_bus_cart['버스체류시간_분'] = (df_bus_cart['하차시각'] - df_bus_cart['승차시각']).astype('timedelta64[m]').astype('int')
df_bus_cart.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16185 entries, 0 to 16184
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   승차시각      16185 non-null  datetime64[ns]
 1   하차시각      16185 non-null  datetime64[ns]
 2   승객구분      16185 non-null  object
 3   환승여부      16185 non-null  object
 4   추가운임여부    16185 non-null  object
 5   승차정류장     16185 non-null  object
 6   하차정류장     16185 non-null  object
 7   버스체류시간_분  16185 non-null  int32
dtypes: datetime64[ns](2), int32(1), object(5)
memory usage: 948.5+ KB

In [33]:
# 이상치 확인
df_bus_cart.describe()

           버스체류시간_분
count  16185.000000
mean      16.345505
std       12.365620
min        0.000000
25%        7.000000
50%       13.000000
75%       22.000000
max       89.000000

#### 버스이용량 분석 항목 생성

In [34]:
# 1. 기준월 및 기준일자별 분석이용량 분석
# 2. 기준일 및 기준시간대별 버스 이용량 분석
# 3. 기준시간 및 시간(분)별 버스 이용량 분석

In [38]:
# 기준년월일시분 항목 생성
df_bus_cart['기준년도'] = df_bus_cart['승차시각'].dt.year
df_bus_cart['기준월'] = df_bus_cart['승차시각'].dt.month
df_bus_cart['기준일'] = df_bus_cart['승차시각'].dt.day
df_bus_cart['기준시간'] = df_bus_cart['승차시각'].dt.hour
df_bus_cart['기준시간_분'] = df_bus_cart['승차시각'].dt.minute
df_bus_cart.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16185 entries, 0 to 16184
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   승차시각      16185 non-null  datetime64[ns]
 1   하차시각      16185 non-null  datetime64[ns]
 2   승객구분      16185 non-null  object
 3   환승여부      16185 non-null  object
 4   추가운임여부    16185 non-null  object
 5   승차정류장     16185 non-null  object
 6   하차정류장     16185 non-null  object
 7   버스체류시간_분  16185 non-null  int32
 8   기준년도      16185 non-null  int64
 9   기준월       16185 non-null  int64
 10  기준일       16185 non-null  int64
 11  기준시간      16185 non-null  int64
 12  기준시간_분    16185 non-null  int64
dtypes: datetime64[ns](2), int32(1), int64(5), object(5)
memory usage: 1.5+ MB

In [40]:
df_bus_cart.head(3)

,승차시각,하차시각,승객구분,환승여부,추가운임여부,승차정류장,하차정류장,버스체류시간_분,기준년도,기준월,기준일,기준시간,기준시간_분
0,2020-01-02 05:10:49,2020-01-02 05:18:44,일반,N,N,양덕차고지,동부초등학교,7,2020,1,2,5,10
1,2020-01-02 05:13:38,2020-01-02 05:45:49,일반,N,N,문덕사거리,새마을금고해도지점,32,2020,1,2,5,13
2,2020-01-02 05:15:49,2020-01-02 05:19:30,일반,N,N,문덕사거리,성우오토모티브,3,2020,1,2,5,15

# ___________________________________

#### 80개파일 통합하기

In [99]:
from datetime import datetime
start_time = datetime.today().strftime('%y-%m-%d %H:%M:%S')
df_bus_card_tot = pd.DataFrame()

In [100]:
# 1.데이터 통합하기

import os
file_path = './bus_crawling/01_data_원본/'

print('Start Time :',datetime.today().strftime('%y-%m-%d %H:%M:%S'))

for i in range(len(os.listdir(file_path))):
    f_path = './bus_crawling/01_data_원본/trfcard ('+ str(i) +')/trfcard.csv'
    csv_tmp = pd.read_csv(f_path)
    df_bus_card_tot = pd.concat([df_bus_card_tot,csv_tmp], ignore_index = True)

print('End Time :',datetime.today().strftime('%y-%m-%d %H:%M:%S'))

Start Time : 23-04-09 10:50:54
End Time : 23-04-09 10:50:57

In [85]:
df_bus_card_tot.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 842608 entries, 0 to 2495
Data columns (total 13 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   on_date      842608 non-null  int64
 1   off_date     842608 non-null  int64
 2   route_name   842608 non-null  object
 3   descr        842608 non-null  object
 4   age_type     842608 non-null  object
 5   trans_yn     842608 non-null  object
 6   addfee_yn    842608 non-null  object
 7   start_bstop  842608 non-null  object
 8   start_gps_x  842608 non-null  float64
 9   start_gps_y  842608 non-null  float64
 10  end_bstop    842608 non-null  object
 11  end_gps_x    842608 non-null  float64
 12  end_gps_y    842608 non-null  float64
dtypes: float64(4), int64(2), object(7)
memory usage: 90.0+ MB

In [101]:
# 2.메타정보 변경
meta_path = './bus_crawling/01_data_원본/trfcard (0)/'
df_bus_card_col_org = pd.read_excel(meta_path + 'trfcard_columns.xlsx',header = 2, usecols=('B:C'))

bus_meta = {}

for x,v in zip(df_bus_card_col_org['컬럼명 (영문)'],df_bus_card_col_org['컬럼명 (한글)']):
    bus_meta[x] = v

df_bus_card_tot.rename(columns = bus_meta, inplace=True)
df_bus_card_tot.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 842608 entries, 0 to 842607
Data columns (total 13 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   승차시각         842608 non-null  int64
 1   하차시각         842608 non-null  int64
 2   노선명          842608 non-null  object
 3   노선설명         842608 non-null  object
 4   승객연령         842608 non-null  object
 5   환승여부         842608 non-null  object
 6   추가운임여부       842608 non-null  object
 7   승차정류장        842608 non-null  object
 8   승차정류장 GPS X  842608 non-null  float64
 9   승차정류장 GPS Y  842608 non-null  float64
 10  하차정류장        842608 non-null  object
 11  하차정류장 GPS X  842608 non-null  float64
 12  하차정류장 GPS Y  842608 non-null  float64
dtypes: float64(4), int64(2), object(7)
memory usage: 83.6+ MB

In [102]:
# 3.타입변경(숫자 - 문자 - 날짜)
print('Start Time :',datetime.today().strftime('%y-%m-%d %H:%M:%S'))

df_bus_card_tot['승차시각'] = pd.to_datetime(df_bus_card_tot['승차시각'].astype('string'))
df_bus_card_tot['하차시각'] = pd.to_datetime(df_bus_card_tot['하차시각'].astype('string'))

print('End Time :',datetime.today().strftime('%y-%m-%d %H:%M:%S'))

df_bus_card_tot.info()

Start Time : 23-04-09 10:51:00
End Time : 23-04-09 10:51:38
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 842608 entries, 0 to 842607
Data columns (total 13 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   승차시각         842608 non-null  datetime64[ns]
 1   하차시각         842608 non-null  datetime64[ns]
 2   노선명          842608 non-null  object
 3   노선설명         842608 non-null  object
 4   승객연령         842608 non-null  object
 5   환승여부         842608 non-null  object
 6   추가운임여부       842608 non-null  object
 7   승차정류장        842608 non-null  object
 8   승차정류장 GPS X  842608 non-null  float64
 9   승차정류장 GPS Y  842608 non-null  float64
 10  하차정류장        842608 non-null  object
 11  하차정류장 GPS X  842608 non-null  float64
 12  하차정류장 GPS Y  842608 non-null  float64
dtypes: datetime64[ns](2), float64(4), object(7)
memory usage: 83.6+ MB

In [88]:
df_bus_card_tot

,승차시각,하차시각,노선명,노선설명,승객연령,환승여부,추가운임여부,승차정류장,승차정류장 GPS X,승차정류장 GPS Y,하차정류장,하차정류장 GPS X,하차정류장 GPS Y
0,2020-01-02 05:10:49,2020-01-02 05:18:44,131,양덕-송도-시청-양학-양덕,일반,N,N,양덕차고지,129.401693,36.077258,동부초등학교,129.380866,36.062209
1,2020-01-02 05:13:38,2020-01-02 05:45:49,175,문덕-고속터미널-선린병원-달전,일반,N,N,문덕사거리,129.403178,35.962298,새마을금고해도지점,129.370626,36.015468
2,2020-01-02 05:15:49,2020-01-02 05:19:30,160,문덕-대송-송도-죽도-용흥,일반,N,N,문덕사거리,129.403442,35.962846,성우오토모티브,129.384492,35.972675
3,2020-01-02 05:16:17,2020-01-02 05:50:46,175,문덕-고속터미널-선린병원-달전,일반,N,N,부영사랑3차,129.402520,35.973038,오거리,129.366312,36.031816
4,2020-01-02 05:18:41,2020-01-02 05:23:10,102,문덕-남구청-고속터미널-북구보건소-양덕,일반,N,N,문덕온천,129.406532,35.961964,용덕사거리,129.415174,35.972826
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2491,2020-03-31 23:15:29,2020-03-31 23:20:33,109,양덕-우현-시외터미널-유강(위덕대)-자명-양덕,일반,N,N,법원사거리,129.387740,36.089380,농협하나로클럽,129.398558,36.081653
2492,2020-03-31 23:16:51,2020-03-31 23:20:54,108,양덕-죽도-양학-시청-유강-지곡,일반,N,N,LG빌라입구,129.317277,36.027317,대잠중앙하이츠,129.338901,36.021808
2493,2020-03-31 23:38:06,2020-03-31 23:45:46,107,문덕-시외(고속)터미널-흥해,일반,N,N,대동우방아파트,129.360209,36.050494,상대시장,129.361983,36.019438
2494,2020-03-31 23:48:33,2020-03-31 23:59:54,175,문덕-고속터미널-선린병원-달전,일반,N,N,해병대서문,129.413196,35.977037,부영사랑3차,129.402238,35.973022
2495,2020-03-31 23:56:43,2020-04-01 00:04:08,102,문덕-남구청-고속터미널-북구보건소-양덕,일반,N,N,해병대서문,129.413196,35.977037,문덕사거리,129.402914,35.962293

In [103]:
# 4. 체류시간
df_bus_card_tot['버스체류시간_분'] = (df_bus_card_tot['하차시각'] - df_bus_card_tot['승차시각']).astype('timedelta64[m]').astype(int)

df_bus_card_tot

,승차시각,하차시각,노선명,노선설명,승객연령,환승여부,추가운임여부,승차정류장,승차정류장 GPS X,승차정류장 GPS Y,하차정류장,하차정류장 GPS X,하차정류장 GPS Y,버스체류시간_분
0,2020-01-02 05:10:49,2020-01-02 05:18:44,131,양덕-송도-시청-양학-양덕,일반,N,N,양덕차고지,129.401693,36.077258,동부초등학교,129.380866,36.062209,7
1,2020-01-02 05:13:38,2020-01-02 05:45:49,175,문덕-고속터미널-선린병원-달전,일반,N,N,문덕사거리,129.403178,35.962298,새마을금고해도지점,129.370626,36.015468,32
2,2020-01-02 05:15:49,2020-01-02 05:19:30,160,문덕-대송-송도-죽도-용흥,일반,N,N,문덕사거리,129.403442,35.962846,성우오토모티브,129.384492,35.972675,3
3,2020-01-02 05:16:17,2020-01-02 05:50:46,175,문덕-고속터미널-선린병원-달전,일반,N,N,부영사랑3차,129.402520,35.973038,오거리,129.366312,36.031816,34
4,2020-01-02 05:18:41,2020-01-02 05:23:10,102,문덕-남구청-고속터미널-북구보건소-양덕,일반,N,N,문덕온천,129.406532,35.961964,용덕사거리,129.415174,35.972826,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
842603,2020-03-31 23:15:29,2020-03-31 23:20:33,109,양덕-우현-시외터미널-유강(위덕대)-자명-양덕,일반,N,N,법원사거리,129.387740,36.089380,농협하나로클럽,129.398558,36.081653,5
842604,2020-03-31 23:16:51,2020-03-31 23:20:54,108,양덕-죽도-양학-시청-유강-지곡,일반,N,N,LG빌라입구,129.317277,36.027317,대잠중앙하이츠,129.338901,36.021808,4
842605,2020-03-31 23:38:06,2020-03-31 23:45:46,107,문덕-시외(고속)터미널-흥해,일반,N,N,대동우방아파트,129.360209,36.050494,상대시장,129.361983,36.019438,7
842606,2020-03-31 23:48:33,2020-03-31 23:59:54,175,문덕-고속터미널-선린병원-달전,일반,N,N,해병대서문,129.413196,35.977037,부영사랑3차,129.402238,35.973022,11
842607,2020-03-31 23:56:43,2020-04-01 00:04:08,102,문덕-남구청-고속터미널-북구보건소-양덕,일반,N,N,해병대서문,129.413196,35.977037,문덕사거리,129.402914,35.962293,7

In [104]:
# 5.항목 생성
df_bus_card_tot['기준년도'] = df_bus_card_tot['승차시각'].dt.year
df_bus_card_tot['기준월'] = df_bus_card_tot['승차시각'].dt.month
df_bus_card_tot['기준일'] = df_bus_card_tot['승차시각'].dt.day
df_bus_card_tot['기준시간'] = df_bus_card_tot['승차시각'].dt.hour
df_bus_card_tot['기준시간_분'] = df_bus_card_tot['승차시각'].dt.minute

df_bus_card_tot

,승차시각,하차시각,노선명,노선설명,승객연령,환승여부,추가운임여부,승차정류장,승차정류장 GPS X,승차정류장 GPS Y,하차정류장,하차정류장 GPS X,하차정류장 GPS Y,버스체류시간_분,기준년도,기준월,기준일,기준시간,기준시간_분
0,2020-01-02 05:10:49,2020-01-02 05:18:44,131,양덕-송도-시청-양학-양덕,일반,N,N,양덕차고지,129.401693,36.077258,동부초등학교,129.380866,36.062209,7,2020,1,2,5,10
1,2020-01-02 05:13:38,2020-01-02 05:45:49,175,문덕-고속터미널-선린병원-달전,일반,N,N,문덕사거리,129.403178,35.962298,새마을금고해도지점,129.370626,36.015468,32,2020,1,2,5,13
2,2020-01-02 05:15:49,2020-01-02 05:19:30,160,문덕-대송-송도-죽도-용흥,일반,N,N,문덕사거리,129.403442,35.962846,성우오토모티브,129.384492,35.972675,3,2020,1,2,5,15
3,2020-01-02 05:16:17,2020-01-02 05:50:46,175,문덕-고속터미널-선린병원-달전,일반,N,N,부영사랑3차,129.402520,35.973038,오거리,129.366312,36.031816,34,2020,1,2,5,16
4,2020-01-02 05:18:41,2020-01-02 05:23:10,102,문덕-남구청-고속터미널-북구보건소-양덕,일반,N,N,문덕온천,129.406532,35.961964,용덕사거리,129.415174,35.972826,4,2020,1,2,5,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
842603,2020-03-31 23:15:29,2020-03-31 23:20:33,109,양덕-우현-시외터미널-유강(위덕대)-자명-양덕,일반,N,N,법원사거리,129.387740,36.089380,농협하나로클럽,129.398558,36.081653,5,2020,3,31,23,15
842604,2020-03-31 23:16:51,2020-03-31 23:20:54,108,양덕-죽도-양학-시청-유강-지곡,일반,N,N,LG빌라입구,129.317277,36.027317,대잠중앙하이츠,129.338901,36.021808,4,2020,3,31,23,16
842605,2020-03-31 23:38:06,2020-03-31 23:45:46,107,문덕-시외(고속)터미널-흥해,일반,N,N,대동우방아파트,129.360209,36.050494,상대시장,129.361983,36.019438,7,2020,3,31,23,38
842606,2020-03-31 23:48:33,2020-03-31 23:59:54,175,문덕-고속터미널-선린병원-달전,일반,N,N,해병대서문,129.413196,35.977037,부영사랑3차,129.402238,35.973022,11,2020,3,31,23,48
842607,2020-03-31 23:56:43,2020-04-01 00:04:08,102,문덕-남구청-고속터미널-북구보건소-양덕,일반,N,N,해병대서문,129.413196,35.977037,문덕사거리,129.402914,35.962293,7,2020,3,31,23,56

In [105]:
len(df_bus_card_tot)

842608

In [107]:
# 파일저장
df_bus_card_tot.to_csv('./bus_crawling/02_data_통합/df_bus_tot.csv', index=None,encoding="cp949")